### ISSUE TITLE
Agency HQ unable to submit approval

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-approvals#189]
![approval](https://user-images.githubusercontent.com/11567315/79273096-75710700-7e70-11ea-9b05-847271ffbcfd.png)

It appears on nr.testing.datim.org that the approvals app is submitting Agency HQ approvals at the OU level, when it should be submitting at global.

**Comment by hardingt** [comment]
@jakub-bao note that nr.testing.datim.org is one minor point release behind prod, so that might be the whole fix

**Comment by hardingt** [comment]
When I upgraded to 2.0.2 I now get this for Agency HQ

![image](https://user-images.githubusercontent.com/11567315/79274658-e4e7f600-7e72-11ea-8dd2-e6a8ad83a104.png)

You can find it at this link:
https://nr.testing.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=YM6xn5QxNpY%3AftafnQZ4uml%3AxaSmIchIF7K%3A&period=2019Oct&workflow=WUD8TApgOu1

**Comment by mpinardi-bao** [comment]
I can validate it does now submit to global from agencyHQ for me. But i also see the same 404 error for the data.

**Comment by hardingt** [comment]
@jakub-bao and @mpinardi-bao I think i know the 404 error:

2.33 changed, and Jakub has two branches for this app. @jakub-bao can you by chance point us to the most up to date 2.33 version of the app?

CC @benguaraldi

**Comment by jakub-bao** [comment]
@hardingt 

The `not being able to submit by agency HQ` is a bug I've removed since.
I've deployed latest `2.0.2` version to `nr.testing` and you can check it's working there:

![image](https://user-images.githubusercontent.com/47790868/79376234-df98b300-7f27-11ea-96d7-9192bfb8f18b.png)
https://nr.testing.datim.org/api/apps/Data-Approval/index.html#/action?approvalCombos=YM6xn5QxNpY%3AftafnQZ4uml%3AxaSmIchIF7K%3A&period=2019Oct&workflow=WUD8TApgOu1

However, as you say, I had a special `2.33` compatible release.
All the special `2.33` release is doing is updated header bar and correct query to `dataset report api`.
That one is right now broken because `2.0.2` is NOT compatible with 2.33:
![image](https://user-images.githubusercontent.com/47790868/79376370-11117e80-7f28-11ea-8e1b-2b381d8745a1.png)

I'll have to prepare a new `2.33` compatible release on top of the new version `2.0.2`.

Should I schedule this sometime soon?

**Comment by jakub-bao** [comment]
@hardingt 
To be clear:
> can you by chance point us to the most up to date 2.33 version of the app?
That would be version `2.0.1` but that one is now very outdated and the ER process still won't be working there.

**Comment by benguaraldi** [comment]
@jakub-bao Yeah, it'd be great to get new 2.33 versions of approvals and user admin at some point.  Is that a high LOE?  When might you be able to fit that in?

**Comment by jakub-bao** [comment]
@benguaraldi 1-2 days LOE. Can do any time. Just let me know when would be a good time to get it ready.

**Comment by benguaraldi** [comment]
@jakub-bao Let's do it either in the middle of or just after the User Admin fixes you're working on, but before returning to Dedupe.  Thanks!

**Comment by hardingt** [comment]
It still seems this is an issue, perhaps it was back burnered for a while while the user admin app was worked on.

**Comment by mpinardi-bao** [comment]
Agency HQ is able to Submit to Global. I didn't see the issue yesterday and just tested again when i saw your comment. This is currently working for me. So please validate if this is an issue on your end. But the global user is only able to edit the mechanisms when the global OU is selected.

**Comment by hardingt** [comment]
@mpinardi-bao I think this was only an issue with Budgets and Jakub provided a quick fix for me. The most up to dat version of the app is in dev.er.datim.org

**Comment by benguaraldi** [comment]
Completed.
